### ISSUE TITLE
Create develop branch and make it default

### ISSUE THREAD

**Issue by zambrovski** [AxonFramework/extension-kotlin#1]
I propose to use gitflow branch model for naming branches.

**Comment by snowe2010** [comment]
I would recommend [OneFlow](https://www.endoflineblog.com/gitflow-considered-harmful), a small difference from GitFlow. The site is currently being migrated I think, but here's a cached version. 

https://web.archive.org/web/20191015033912/https://www.endoflineblog.com/gitflow-considered-harmful
https://web.archive.org/web/20190620093748/http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow

**Comment by jangalinski** [comment]
I would propose to use the same repository management, branch model, build system and work organization as the main module in this org.

**Comment by zambrovski** [comment]
Good point. Then we should stick on master as default branch.
