### ISSUE TITLE
Release mvp?

### ISSUE THREAD

**Issue by jangalinski** [AxonFramework/extension-kotlin#26]
Although there is a lot to do ... shouldn't we just release an 0.1.0, so we can start using this in our projects?

**Comment by smcvb** [comment]
Planning to do this ASAP indeed. Guessing next week or so, right @sandjelkovic?

**Comment by sandjelkovic** [comment]
That is our intention @jangalinski to release an experimental version soon. Hopefully sometime during next week.

**Comment by jangalinski** [comment]
Wow, that's good news ... looking forward to

**Comment by smcvb** [comment]
We've just released 0.1.0! So I feel we can close this issue. :-)
