### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by Blackdread** [AxonFramework/extension-kotlin#9]
Just some extension I use:

- QueryTyped:
`interface QueryTyped<R>`

- QueryGatewayExtension:
```
inline fun <reified T> QueryGateway.queryTyped(query: QueryTyped<T>): CompletableFuture<T> {
    return query(query, T::class.java)
}

inline fun <R: List<T>, reified T> QueryGateway.queryTypedList(query: QueryTyped<R>): CompletableFuture<List<T>> {
    return query(query, ResponseTypes.multipleInstancesOf(T::class.java))
}

// ...
```

I have similar extensions for command gateway as well.

- CommandTyped:
`interface CommandTyped<R>`

And some other extensions

**Comment by sandjelkovic** [comment]
Thanks for the suggestion @Blackdread .
Can you please provide a sample usage of `QueryTyped` and `CommandTyped` with the mentioned extensions?

There are a couple of QueryGateway extensions implemented which can be found [here](https://github.com/AxonFramework/extension-kotlin/blob/master/kotlin/src/main/kotlin/org/axonframework/extensions/kotlin/QueryGatewayExtensions.kt) that are using reified generics to proxy the call to QueryGateway. 
Currently only variations which require the name of the queries are provided.
However in the future it would be beneficial to also provide variants that are using the method with just the query parameter that would proxy to [this method](https://github.com/AxonFramework/AxonFramework/blob/master/messaging/src/main/java/org/axonframework/queryhandling/QueryGateway.java#L84).

**Comment by Blackdread** [comment]
Define `QueryTyped.kt`:
```
interface QueryTyped<R>
```

Define `CommandTyped.kt`:
```
interface CommandTyped<R>
```

Define `CommandGatewayExtension.kt`:
```
// allow to send a command, ignoring the return type (usually the id) but not ignoring exceptions
fun CommandGateway.sendVoid(command: Any): CompletableFuture<Void> {
    return this.send<Any>(command)
        .thenApply { null }
}

fun <T> CommandGateway.sendTyped(command: CommandTyped<T>): CompletableFuture<T> {
    return this.send<T>(command)
}

fun <T> CommandGateway.sendAndWaitTyped(command: CommandTyped<T>): T {
    return this.sendAndWait(command)
}

```
I have some other extensions but more related to spring, some of those extensions takes `Function<T, ResponseEntity<T>>` to auto map the command result into a response entity, other to auto map to Void (while not ignoring the exception if command failed), return empty response ignoring data from command (does not ignore exception if any), auto map an optional return type to a 404 ResponseEntity, etc.


Define `QueryGatewayExtension.kt`:
```
inline fun <reified T> QueryGateway.queryTyped(query: QueryTyped<T>): CompletableFuture<T> {
    return query(query, T::class.java)
}

inline fun <R : List<T>, reified T> QueryGateway.queryTypedList(query: QueryTyped<R>): CompletableFuture<List<T>> {
    return query(query, ResponseTypes.multipleInstancesOf(T::class.java))
}


inline fun <R : Optional<T>, reified T> QueryGateway.queryTypedOptional(query: QueryTyped<R>): CompletableFuture<Optional<T>> {
    return query(query, ResponseTypes.optionalInstanceOf(T::class.java))
}
```


In some RestController/Service/etc:
```
@RestController
@RequestMapping("/api/example")
class ExampleController {


    @Autowired
    private lateinit var queryGateway: QueryGateway

    @Autowired
    private lateinit var commandGateway: CommandGateway
	
	
    @PostMapping
    fun create(/* put @RequestBody with VM */): CompletableFuture<ExampleId>{
		return commandGateway.sendTyped(CreateExampleCommand(ExampleId(), "etc"))
	}
	
	
    @GetMapping
    fun getAll(): CompletableFuture<List<ExampleDTO>>{
		return queryGateway.queryTypedList(FindAllExample)
	}
	
	
    @GetMapping("/{id}")
    fun getById(@PathVariable id: ExampleId): CompletableFuture<ExampleDTO>{
		return queryGateway.queryTypedOptional(FindExampleById(id))
	}

    @GetMapping("/data")
    fun getById(): CompletableFuture<ExampleDTO?>{
        return queryGateway.queryTyped(FindExampleByData(1L))
    }
}

inline class ExampleId(val identifier: String = IdentifierFactory.getInstance().generateIdentifier())

data class CreateExampleCommand(
	val exampleId: ExampleId,
	val someData: String
) : CommandTyped<ExampleId>

object FindAllExample : QueryTyped<List<ExampleDTO>>

data class FindExampleById(val exampleId: ExampleId) : QueryTyped<Optional<ExampleDTO>>

data class FindExampleByData(val someOtherData: Long) : QueryTyped<ExampleDTO?>

data class ExampleDTO(
	val exampleId: ExampleId,
	val someData: Set<String>,
	val someData2: Set<NestedDTO>
){
	
	data class NestedDTO(
		val other: Long,
		val other2: Boolean
	)

}
```

**Comment by sandjelkovic** [comment]
Thank you for the examples and clarification.

The approach you took is interesting, however, if something like this would exist on the extension level, it would introduce a constraint on everyone to have to implement those interfaces to use Kotlin extensions on the gateways.
With the current approach, you can use anything as a Query object and request the Response type via a reified generic in the method call, which can also be potentially inferred by the compiler.
