### ISSUE TITLE
Fixture factories can not be used as factory methods

### ISSUE THREAD

**Issue by sandjelkovic** [AxonFramework/extension-kotlin#92]
### Basic information

* Axon Framework version: -
* JDK version:  -
* Kotlin Extension version: 0.2.0-SNAPSHOT
* Complete executable reproducer if available (e.g. GitHub Repo):

### Steps to reproduce

Try to use call reified `aggregateTestFixture` or reified `sagaTestFixture` as a factory method, meaning without an already created fixture instance.

### Expected behaviour

Use these methods as they were intended to - factory methods to create new Fixtures. 

`var fixture: AggregateTestFixture<MyAggregate> = aggregateTestFixture()`

These methods can not be extensions to already existing fixtures but should be simple standalone functions that use reified generics.

More information can be found here https://github.com/AxonFramework/extension-kotlin/pull/73#discussion_r540417428

**Comment by Arnaud-J** [comment]
@sandjelkovic Here it is: https://github.com/AxonFramework/extension-kotlin/pull/93
